name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4
      - uses: actions/setup-java@v4 # Updated to v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # This creates the necessary Android folders automatically
      - run: flutter create . --platforms android
      
      - run: flutter pub get
      - run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4 # This was the error! Now updated to v4
        with:
          name: Chandrama-Masala-App
          path: build/app/outputs/flutter-apk/app-release.apk
